# Generated by Django 6.1.1 on 2026-09-25 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("file", models.FileField(upload_to="documents/")),
                (
                    "regulator",
                    models.CharField(
                        choices=[("RBI", "RBI"), ("SEBI", "SEBI")],
                        default="RBI",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_force", "In Force"),
                            ("amended", "Amended"),
                            ("repealed", "Repealed"),
                        ],
                        default="in_force",
                        max_length=20,
                    ),
                ),
                ("effective_date", models.DateField(blank=True, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_indexed",
                    models.BooleanField(
                        default=False,
                        help_text="Whether chunks have been embedded and indexed",
                    ),
                ),
                ("total_chunks", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="EvalRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("run_at", models.DateTimeField(auto_now_add=True)),
                ("total_questions", models.IntegerField(default=0)),
                ("correct_retrievals", models.IntegerField(default=0)),
                ("correct_refusals", models.IntegerField(default=0)),
                ("false_answers", models.IntegerField(default=0)),
                ("avg_response_time_ms", models.FloatField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="GoldQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                (
                    "expected_answer",
                    models.TextField(
                        help_text="Expected answer text (for manual comparison)"
                    ),
                ),
                (
                    "expected_paragraph_ids",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of paragraph IDs that should be retrieved",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("direct", "Direct Lookup"),
                            ("multi_para", "Multi-Paragraph"),
                            ("unanswerable", "Unanswerable"),
                        ],
                        default="direct",
                        max_length=20,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="qa.document",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EvalResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("system_answer", models.TextField(blank=True)),
                ("retrieved_chunk_ids", models.JSONField(blank=True, default=list)),
                ("retrieval_correct", models.BooleanField(default=False)),
                (
                    "answer_quality",
                    models.CharField(
                        choices=[
                            ("correct", "Correct"),
                            ("partial", "Partially Correct"),
                            ("wrong", "Wrong"),
                            ("refused", "Correctly Refused"),
                            ("false_refuse", "Incorrectly Refused"),
                        ],
                        default="wrong",
                        max_length=20,
                    ),
                ),
                ("response_time_ms", models.IntegerField(blank=True, null=True)),
                (
                    "eval_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="qa.evalrun",
                    ),
                ),
                (
                    "gold_question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="qa.goldquestion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QueryLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("answer", models.TextField(blank=True)),
                ("retrieved_chunk_ids", models.JSONField(blank=True, default=list)),
                ("confidence_scores", models.JSONField(blank=True, default=list)),
                ("citation_verified", models.BooleanField(default=False)),
                (
                    "flagged",
                    models.BooleanField(
                        default=False, help_text="True if citation check found issues"
                    ),
                ),
                (
                    "not_found",
                    models.BooleanField(
                        default=False, help_text='True if system said "not found"'
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("response_time_ms", models.IntegerField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Chunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chunk_index",
                    models.IntegerField(
                        help_text="Sequential index of this chunk in the document"
                    ),
                ),
                (
                    "paragraph_id",
                    models.CharField(
                        blank=True, help_text='e.g. "3.1", "4(a)(ii)"', max_length=100
                    ),
                ),
                ("text", models.TextField()),
                ("page_number", models.IntegerField(blank=True, null=True)),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extra metadata (heading hierarchy, etc.)",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="qa.document",
                    ),
                ),
            ],
            options={
                "ordering": ["document", "chunk_index"],
                "unique_together": {("document", "chunk_index")},
            },
        ),
    ]
