# Generated by Django 4.2.30 on 2026-10-03 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('abstained', 'Abstained'), ('failed', 'Failed')], default='running', max_length=12)),
                ('plan_summary', models.TextField(blank=True)),
                ('sub_questions', models.JSONField(blank=True, default=list)),
                ('final_answer_payload', models.JSONField(blank=True, default=dict)),
                ('step_count', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='GapAnalysisRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=10)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('corpus_fingerprint', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('counts', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('run_gap_analysis', 'Can run gap analyses')],
            },
        ),
        migrations.CreateModel(
            name='VectorIndexBuild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation_id', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('building', 'Building'), ('ready', 'Ready'), ('failed', 'Failed'), ('superseded', 'Superseded')], db_index=True, default='building', max_length=12)),
                ('embedding_model', models.CharField(max_length=200)),
                ('vector_dimension', models.IntegerField()),
                ('distance_metric', models.CharField(default='inner_product', max_length=30)),
                ('normalized_embeddings', models.BooleanField(default=True)),
                ('chunker_version', models.CharField(blank=True, max_length=50)),
                ('corpus_fingerprint', models.CharField(blank=True, max_length=64)),
                ('vector_count', models.IntegerField(default=0)),
                ('build_started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('build_finished_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('triggered_by', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['-build_started_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-uploaded_at'], 'permissions': [('upload_document', 'Can upload documents'), ('index_document', 'Can index/re-index documents'), ('manage_corpus', 'Can manage the corpus and vector index')]},
        ),
        migrations.AlterModelOptions(
            name='goldquestion',
            options={'permissions': [('run_evaluation', 'Can run evaluations')]},
        ),
        migrations.AlterModelOptions(
            name='querylog',
            options={'ordering': ['-created_at'], 'permissions': [('view_global_logs', "Can view all users' query logs")]},
        ),
        migrations.AddField(
            model_name='chunk',
            name='chunker_version',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='chunk',
            name='content_sha256',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='chunk',
            name='end_page',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chunk',
            name='heading_path',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='chunk',
            name='printed_end_page',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='chunk',
            name='printed_start_page',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='chunk',
            name='start_page',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('regulation', 'Regulatory source'), ('company_policy', 'Company policy')], db_index=True, default='regulation', max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='index_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='document',
            name='index_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('error', 'Error')], db_index=True, default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='document',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='document',
            name='page_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='printed_page_offset',
            field=models.IntegerField(default=0, help_text='Printed page = PDF page + offset (when a fixed offset applies).'),
        ),
        migrations.AddField(
            model_name='document',
            name='publication_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='sha256',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='document',
            name='source_category',
            field=models.CharField(choices=[('unclassified', 'Unclassified'), ('binding_regulation', 'Binding regulation'), ('master_direction', 'Master direction'), ('circular', 'Circular'), ('consultation_paper', 'Consultation paper / draft circular'), ('guidance', 'Guidance'), ('report', 'Research or financial-stability report'), ('internal_policy', 'Internal company policy')], default='unclassified', max_length=30),
        ),
        migrations.AddField(
            model_name='document',
            name='source_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='document',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='version_label',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='evalresult',
            name='answer_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='evalresult',
            name='citation_precision',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evalresult',
            name='correctness_label',
            field=models.CharField(choices=[('correct', 'Correct'), ('partial', 'Partial'), ('wrong', 'Wrong'), ('not_judged', 'Not judged')], default='not_judged', max_length=12),
        ),
        migrations.AddField(
            model_name='evalresult',
            name='correctness_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evalresult',
            name='error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='evalresult',
            name='estimated_cost',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='evalresult',
            name='faithfulness_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evalresult',
            name='hit_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evalresult',
            name='human_correctness_label',
            field=models.CharField(blank=True, choices=[('correct', 'Correct'), ('partial', 'Partial'), ('wrong', 'Wrong'), ('not_judged', 'Not judged')], max_length=12),
        ),
        migrations.AddField(
            model_name='evalresult',
            name='judge_explanation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='evalresult',
            name='judge_model',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='evalresult',
            name='judge_prompt_version',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='evalresult',
            name='recall_at_k',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evalresult',
            name='refusal_correct',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evalresult',
            name='refused',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='evalresult',
            name='retrieved_evidence',
            field=models.JSONField(blank=True, default=list, help_text='Ranked [{document_id, paragraph_id, chunk_id, scores}]'),
        ),
        migrations.AddField(
            model_name='evalresult',
            name='unsupported_claim_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='evalrun',
            name='answer_correctness',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evalrun',
            name='citation_precision',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evalrun',
            name='configuration',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='evalrun',
            name='correct_refusal_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evalrun',
            name='estimated_cost',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='evalrun',
            name='faithfulness',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evalrun',
            name='false_refusal_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evalrun',
            name='label',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='evalrun',
            name='median_latency_ms',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evalrun',
            name='p95_latency_ms',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evalrun',
            name='retrieval_hit_at_1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evalrun',
            name='retrieval_hit_at_3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evalrun',
            name='retrieval_hit_at_k',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evalrun',
            name='retrieval_mrr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evalrun',
            name='retrieval_recall_at_k',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evalrun',
            name='status',
            field=models.CharField(default='complete', max_length=12),
        ),
        migrations.AddField(
            model_name='goldquestion',
            name='expected_answer_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='goldquestion',
            name='gold_set_version',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='goldquestion',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='goldquestion',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goldquestion',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_gold_questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='goldquestion',
            name='split',
            field=models.CharField(choices=[('dev', 'Development'), ('test', 'Held-out test')], db_index=True, default='dev', max_length=10),
        ),
        migrations.AddField(
            model_name='querylog',
            name='agent_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='querylog',
            name='answer_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='querylog',
            name='citation_precision',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='querylog',
            name='confidence_band',
            field=models.CharField(blank=True, choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('insufficient', 'Insufficient')], db_index=True, max_length=15),
        ),
        migrations.AddField(
            model_name='querylog',
            name='error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='querylog',
            name='estimated_cost',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='querylog',
            name='faithfulness_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='querylog',
            name='model_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='querylog',
            name='prompt_version',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='querylog',
            name='retrieval_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='querylog',
            name='review_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='querylog',
            name='review_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='querylog',
            name='review_required',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='querylog',
            name='review_status',
            field=models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='open', max_length=10),
        ),
        migrations.AddField(
            model_name='querylog',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='querylog',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_queries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='document',
            name='regulator',
            field=models.CharField(blank=True, choices=[('RBI', 'RBI'), ('SEBI', 'SEBI')], default='RBI', max_length=10),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('in_force', 'In Force'), ('amended', 'Amended'), ('repealed', 'Repealed'), ('draft', 'Draft / Consultation'), ('not_applicable', 'Not applicable')], default='in_force', max_length=20),
        ),
        migrations.AlterField(
            model_name='evalresult',
            name='answer_quality',
            field=models.CharField(choices=[('correct', 'Correct'), ('partial', 'Partially Correct'), ('wrong', 'Wrong'), ('refused', 'Correctly Refused'), ('false_refuse', 'Incorrectly Refused'), ('not_judged', 'Not judged')], default='wrong', max_length=20),
        ),
        migrations.AlterField(
            model_name='goldquestion',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='qa.document'),
        ),
        migrations.AlterField(
            model_name='goldquestion',
            name='expected_answer',
            field=models.TextField(help_text='Reference answer text'),
        ),
        migrations.AlterField(
            model_name='goldquestion',
            name='expected_paragraph_ids',
            field=models.JSONField(blank=True, default=list, help_text='DEPRECATED — use Gold evidence rows instead.'),
        ),
        migrations.AlterField(
            model_name='querylog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='querylog',
            name='not_found',
            field=models.BooleanField(default=False, help_text='True if the system abstained'),
        ),
        migrations.CreateModel(
            name='ObligationExtractionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_sha256', models.CharField(max_length=64)),
                ('prompt_version', models.CharField(max_length=50)),
                ('model_name', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('done', 'Done'), ('error', 'Error')], max_length=10)),
                ('obligation_count', models.IntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('review_status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='open', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chunk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='qa.chunk')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extraction_records', to='qa.document')),
            ],
        ),
        migrations.CreateModel(
            name='Obligation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_paragraph_id', models.CharField(blank=True, max_length=100)),
                ('source_content_sha256', models.CharField(blank=True, db_index=True, max_length=64)),
                ('source_start_page', models.PositiveIntegerField(blank=True, null=True)),
                ('source_end_page', models.PositiveIntegerField(blank=True, null=True)),
                ('source_printed_pages', models.CharField(blank=True, max_length=50)),
                ('source_quote', models.TextField(blank=True)),
                ('quote_verified', models.BooleanField(default=False)),
                ('obligation_text', models.TextField()),
                ('obligated_party', models.CharField(blank=True, db_index=True, max_length=300)),
                ('condition', models.TextField(blank=True)),
                ('deadline_or_trigger', models.TextField(blank=True)),
                ('extraction_confidence', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('insufficient', 'Insufficient')], db_index=True, default='low', max_length=15)),
                ('extraction_model', models.CharField(blank=True, max_length=200)),
                ('prompt_version', models.CharField(blank=True, max_length=50)),
                ('entailment_status', models.CharField(choices=[('entailed', 'Entailed by source'), ('partial', 'Partially entailed'), ('not_entailed', 'Not entailed'), ('unavailable', 'Check unavailable')], db_index=True, default='unavailable', max_length=15)),
                ('entailment_explanation', models.TextField(blank=True)),
                ('review_status', models.CharField(choices=[('pending', 'Pending review'), ('confirmed', 'Confirmed'), ('edited', 'Edited & confirmed'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewer_notes', models.TextField(blank=True)),
                ('original_values', models.JSONField(blank=True, default=dict, help_text='Extractor output before edits')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_obligations', to=settings.AUTH_USER_MODEL)),
                ('source_chunk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obligations', to='qa.chunk')),
                ('source_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obligations', to='qa.document')),
            ],
            options={
                'ordering': ['source_document', 'source_start_page', 'id'],
                'permissions': [('review_obligation', 'Can review extracted obligations'), ('extract_obligations', 'Can run obligation extraction')],
            },
        ),
        migrations.CreateModel(
            name='GoldEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph_id', models.CharField(max_length=100)),
                ('text_anchor', models.CharField(blank=True, help_text='Short verbatim phrase from the evidence passage; disambiguates repeated paragraph IDs.', max_length=300)),
                ('required', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('chunk', models.ForeignKey(blank=True, help_text='Convenience pointer only; chunk IDs change on re-index.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='qa.chunk')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gold_evidence', to='qa.document')),
                ('gold_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='qa.goldquestion')),
            ],
        ),
        migrations.CreateModel(
            name='GapFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('addressed', 'Addressed'), ('partially_addressed', 'Partially addressed'), ('not_addressed', 'Potential gap — not addressed'), ('conflicting', 'Potential conflict'), ('needs_review', 'Needs review')], db_index=True, max_length=20)),
                ('explanation', models.TextField(blank=True)),
                ('regulatory_evidence', models.JSONField(blank=True, default=dict)),
                ('policy_evidence', models.JSONField(blank=True, default=dict)),
                ('candidate_policy_chunk_ids', models.JSONField(blank=True, default=list)),
                ('model_name', models.CharField(blank=True, max_length=200)),
                ('prompt_version', models.CharField(blank=True, max_length=50)),
                ('confidence_band', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('insufficient', 'Insufficient')], default='low', max_length=15)),
                ('review_status', models.CharField(choices=[('pending', 'Pending review'), ('accepted', 'Accepted'), ('overridden', 'Overridden')], db_index=True, default='pending', max_length=12)),
                ('reviewer_status_override', models.CharField(blank=True, choices=[('addressed', 'Addressed'), ('partially_addressed', 'Partially addressed'), ('not_addressed', 'Potential gap — not addressed'), ('conflicting', 'Potential conflict'), ('needs_review', 'Needs review')], max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewer_notes', models.TextField(blank=True)),
                ('error', models.TextField(blank=True)),
                ('matched_policy_chunk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='qa.chunk')),
                ('obligation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gap_findings', to='qa.obligation')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='qa.gapanalysisrun')),
            ],
            options={
                'ordering': ['run', 'id'],
            },
        ),
        migrations.AddField(
            model_name='gapanalysisrun',
            name='policy_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gap_runs_as_policy', to='qa.document'),
        ),
        migrations.AddField(
            model_name='gapanalysisrun',
            name='regulatory_documents',
            field=models.ManyToManyField(blank=True, related_name='gap_runs_as_regulation', to='qa.document'),
        ),
        migrations.CreateModel(
            name='AgentStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('step_type', models.CharField(choices=[('plan', 'Plan'), ('tool', 'Tool call'), ('synthesis', 'Synthesis'), ('decision', 'Decision')], max_length=12)),
                ('tool_name', models.CharField(blank=True, max_length=50)),
                ('tool_input', models.JSONField(blank=True, default=dict)),
                ('output_summary', models.TextField(blank=True)),
                ('evidence_chunk_ids', models.JSONField(blank=True, default=list)),
                ('latency_ms', models.IntegerField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='qa.agentrun')),
            ],
            options={
                'ordering': ['run', 'position'],
            },
        ),
        migrations.AddField(
            model_name='agentrun',
            name='query_log',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_run', to='qa.querylog'),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='obligationextractionrecord',
            constraint=models.UniqueConstraint(fields=('document', 'content_sha256', 'prompt_version'), name='unique_extraction_record'),
        ),
        migrations.AddConstraint(
            model_name='goldevidence',
            constraint=models.UniqueConstraint(fields=('gold_question', 'document', 'paragraph_id'), name='unique_gold_evidence'),
        ),
        migrations.AlterUniqueTogether(
            name='agentstep',
            unique_together={('run', 'position')},
        ),
    ]
