# Generated by Django 4.2.30 on 2026-10-03 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qa', '0003_backfill_upgrade_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='version_family',
            field=models.CharField(blank=True, help_text='Shared rule identifier across dated versions.', max_length=100),
        ),
        migrations.AddField(
            model_name='obligationextractionrecord',
            name='review_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='obligationextractionrecord',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obligationextractionrecord',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
